# Generated by Django 5.0 on 2024-02-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
