# Generated by Django 5.0 on 2024-02-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_request', '0002_alter_servicerequest_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={},
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='message',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
