# Generated by Django 5.0 on 2024-02-23 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_request', '0003_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='title',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_choice',
            field=models.CharField(choices=[('limpeza_residencial', 'Limpeza Residencial - Serviço de limpeza completa de residências, incluindo aspiração, limpeza de superfícies, banheiros, cozinha e remoção de poeira.'), ('manutencao_jardim', 'Manutenção de Jardim - Serviço de manutenção e cuidados com jardins, incluindo corte de grama, poda de plantas, remoção de ervas daninhas e fertilização.'), ('reparos_eletricos', 'Reparos Elétricos - Serviço de reparo e instalação elétrica em residências, incluindo troca de tomadas, interruptores, instalação de luminárias e solução de problemas elétricos simples.')], default='limpeza_residencial', max_length=20),
        ),
    ]
