# Generated by Django 5.0 on 2024-02-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_request', '0005_alter_servicerequest_service_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(default='Pendente', max_length=20),
        ),
    ]
