# Generated by Django 5.0 on 2024-02-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_request', '0006_servicerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='status',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
