# Generated by Django 5.0 on 2024-02-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_request', '0007_remove_servicerequest_status_servicerequest_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_choice',
            field=models.CharField(choices=[('limpeza_residencial', 'Limpeza Residencial - Serviço de limpeza completa de residências, incluindo aspiração, limpeza de superfícies, banheiros, cozinha e remoção de poeira.'), ('manutencao_jardim', 'Manutenção de Jardim - Serviço de manutenção e cuidados com jardins, incluindo corte de grama, poda de plantas, remoção de ervas daninhas e fertilização.'), ('reparos_eletricos', 'Reparos Elétricos - Serviço de reparo e instalação elétrica em residências, incluindo troca de tomadas, interruptores, instalação de luminárias e solução de problemas elétricos simples.')], max_length=20),
        ),
    ]
