# Generated by Django 5.0 on 2024-02-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
