# Generated by Django 5.0 on 2024-02-20 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_first_name_client_name_remove_client_email_and_more'),
        ('clients', '0004_remove_client_enabled'),
    ]

    operations = [
    ]
